[mcp_servers.unity-mcp]
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 300
url = "http://127.0.0.1:8080/"

[mcp_servers.ai-game-developer.tools.assets-refresh]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.script-execute]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.scene-save]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-open]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.assets-prefab-close]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-add]
approval_mode = "approve"

[mcp_servers.blender]
command = 'C:\Users\wamiq\.local\bin\uvx.exe'
args = ["blender-mcp"]

[mcp_servers.ai-game-developer]
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 300
url = "http://localhost:26566/p/a1370f8e"